### ISSUE TITLE
Paralells halts Mac when you start or resume while littleflocker is enabled.

### ISSUE THREAD

**Issue by RawInfoSec** [jzdziarski/littleflocker#12]
Machine locks up when starting or resuming Paralells VM at some point during initialization. Requires hard reset of the Mac, keyboard unresponsive though mouse moves. Menu status icons frozen too.

Halts 100% of the time when little flocker is enabled, but works every time is disabled.

**Comment by jzdziarski** [comment]
Hmm odd, VMware seems okay... does it produce any kernel panic logs or anything else of the sort? I may have to grab a trial to play with.

**Comment by RawInfoSec** [comment]
Didn't find any logs, however I performed a few more tests to help.

- the halt occurs exactly when a VM switches to full screen mode (if it was in that state before it was suspended)
- the halt affects only WindowServer, as I was able to SSH to the laptop while it appeared otherwise unresponsive.
- if you leave it for about 5-6 minutes, WindowServer does indeed restart on its own. It breaks the VM's full screen (adds a blank screen on desktop Spaces)

When WindowServer restarts, a LittleFlocker window was waiting, asking permission for WindowServer to access the InfoPlist inside the VM container. This is probably what is breaking it. I'll confirm via more tests. May be wise for Parallels users to manually add access to the VM container folder for WindowServer running under launchd if it does work.

kc/

**Comment by RawInfoSec** [comment]
I got nowhere.  It's Parallels Desktop 11. Hope that helps. No big deal for me to temp-disable littleflocker before going full screen or resuming a full screen instance.

**Comment by jzdziarski** [comment]
What was the prompt? It sounds like something needs to be added to the default rules to allow it's window server to read that plist.

**Comment by RawInfoSec** [comment]
![screen shot 2016-08-19 at 1 57 54 am](https://cloud.githubusercontent.com/assets/12751893/17814832/8d40c8b2-65ff-11e6-95e0-c8fe86a1b302.png)

**Comment by jzdziarski** [comment]
aha... can you try adding this to your master config and reboot?

allow prefix "any" "/System/Library/Frameworks/CoreGraphics.framework/" rwc

**Comment by RawInfoSec** [comment]
Here's the problem though, none of the WindowServer entries I added last night via LittleFlocker pop-ups are in the .littleflockerrc file.

I will test adding that line next.

**Comment by jzdziarski** [comment]
probably because it's crashing before it can allow the operation, add that to your master config at /Library/Application Support/LittleFlocker/.flockflockrc and then reboot

**Comment by RawInfoSec** [comment]
Worked. Sorry I should have noticed that the WindowServer entries weren't added last night and added it manually. It's working fine now it seems, both VM's loaded and responsive.

**Comment by jzdziarski** [comment]
Great! I'll add that to the default ruleslist then, it probably ought to be in there anyway. Thanks.
