### ISSUE TITLE
Question: /usr/local for initial watch rules?

### ISSUE THREAD

**Issue by JayBrown** [jzdziarski/littleflocker#15]
I haven't yet installed Little Flocker, but I will eventually. Looks like a great piece of software. One question up front: wouldn't it be wise to add /usr/local to the initial watch rules? Example: if users install homebrew, it only works if it's chowned from default root to admin, and most even do it recursively for the whole /usr/local. In these cases anyone can write to one of the subfolders, anyone can change scripts, run binaries etc.

PS: I'm wondering how this works together with other security apps like BlockBlock, RansomWhere, Santa etc. Anyone with experiences?

**Comment by jzdziarski** [comment]
Hi there,

Little Flocker isn't really designed to prevent installation of malware; a good tool for that would be BlockBlock. Little Flocker is designed more to prevent unauthorized access to your data files, anticipating malware will somehow get onto the system. Of course, you could probably add rules like that to your .littleflockerrc file to protect those areas, but that's when we start treading on BlockBlock's territory, and it's probably much better to just specialize for the purpose I designed it for.

With that said, LF does protect certain system areas like /Library/Extensions and /Library/LaunchDaemons, but this is more to try and prevent malware from disabling Little Flocker.

Please feel free to re-open this if you have any other questions!

Jonathan
