### ISSUE TITLE
upgrade failed from 67 to 71 permission denied errors

### ISSUE THREAD

**Issue by zigmund007** [jzdziarski/littleflocker#24]
[install.log.txt](https://github.com/jzdziarski/littleflocker/files/440566/install.log.txt)

Did an upgrade from .67 to .71. Got installation failed error. 
After enabling and disabled little flocker installation upgrade  went succesfull. Don't know why,
previous upgrades were all succesfull. install.log attached

Thank you for writing this piece of excellent software
Zigmund

**Comment by jzdziarski** [comment]
Please let me know if you run into this again upgrading to .72 (which should come to you through Sparkle). Thanks!
