### ISSUE TITLE
Incorrect matching of file extensions

### ISSUE THREAD

**Issue by vivami** [jzdziarski/littleflocker#25]
In some cases, when a file consists of xxx.yy.extension, LF does not match correctly on extension. Screenshot below shows an example, in which I'd like to select "Only .dmg", but is only letting me do `0.75.dmg` files. Same happens for default screenshot naming (`Screen Shot YYYY-MM-DD.png`). The may be resolved by creating a dictionary of commonly used file types?

![](https://cl.ly/hHKD/Screen%20Shot%202016-08-29%20at%2009.34.28.png)

**Comment by jzdziarski** [comment]
thanks, I committed a fix and should be working in 0.0.76
