### ISSUE TITLE
Change radio button in prompt using keys

### ISSUE THREAD

**Issue by vivami** [jzdziarski/littleflocker#26]
I'd be nice if it is possible (just like in Little Snitch) to change the radio buttons/options of a prompt with keys, in addition to clicking with the mouse. 
For example: 
Once: `o`
Until Quit: `q`
Until Restart: `r`
Forever: `f`

Allow: `a`
Deny: `d`

**Comment by jzdziarski** [comment]
Would like to add this, I'm not sure it's possible / elegant using the CFUserNotification windows LF uses now. Will keep this open for possible future implementation of traditional windows.

**Comment by creedflan738** [comment]
nearly as fast to tab through them and use the spacebar to toggle

**Comment by kiancheong** [comment]
@jzdziarski If you add this, could you please ensure that modifier keys are required in order to avoid accidental selections? For example, Cmd+Enter in Little Snitch automatically selects Allow. 

Cheers.

**Comment by jzdziarski** [comment]
figured out a secure way to do a custom window from agent land, more to come, but for now this is done and in svn.

**Comment by tomtastic** [comment]
To echo @kiancheong, can we require modifier keys for these character options, or LS steals away input for several characters into other windows you may be typing in.
eg. a Terminal window can have focus but not a full alphabet to type with...
```
$
$ abcde ghijklmn p  stuvwxyz
```
