### ISSUE TITLE
Feature Request: Log allowed files for certain apps

### ISSUE THREAD

**Issue by TheInnerParty** [jzdziarski/littleflocker#27]
A useful option might be to have little flocker log all file interactions for certain (or even all) apps.. in addition to being a valuable tool to monitor app behaviour more closely, this would allow users to give more lenient permissions to certain apps that make a lot of requests while still keeping some degree of accountability. It would also allow little flocker to be used in a monitoring only mode (like little snitch allows) on computers where having pop ups all the time isn't desirable/ possible. 

Great work on this, it's really impressive!

**Comment by jzdziarski** [comment]
Have thought about adding a monitor mode specifically for this reason, which would also help with system rules development.

**Comment by jzdziarski** [comment]
The new "learning mode" just pushed in beta 2 does something similar to this, and creates a recommended rules list presented to the user when learning is completed / turned off.
