### ISSUE TITLE
csrutil enable --without kext - "requesting an unsupported configuration" 

### ISSUE THREAD

**Issue by necrevistonnezr** [jzdziarski/littleflocker#28]
Hi, trying to install littleflocker on macOS Sierra beta 8.
If I type the command `csrutil enable --without kext` in recovery mode into the terminal, I get the following responst 
> requesting an unsupported configuration. This is likely to break in the future and leave your machine in an unknown state.

**Comment by jzdziarski** [comment]
Hello,
This is normal when disabling kext signing in SIP and will be an unnecessary step when Apple issues a certificate to sign the kernel extension. Please note, Little Flocker is still in development phase and intended for advanced users at this stage. While it appears to be stable, you may run into issues that require some assistance to resolve.
