### ISSUE TITLE
folder permission /Users/Shared/Little\ Flocker denied for non admin users

### ISSUE THREAD

**Issue by zigmund007** [jzdziarski/littleflocker#29]
upgraded to 0.1.2. 
When logged in as a admin user, I can enable/disable simple mode and edit the rules

when logged in as standard user, I'm not able to edit rules and not able to switch mode
I noticed the folder permission of /Users/Share/Little\ Flocker is not accessable for standard users
drwxrwx---  6 root   admin  204 Aug 31 22:20 Little Flocker
I changed the folder permission with chmod o+rwx 
drwxrwxrwx  6 root   admin  204 Aug 31 22:20 Little Flocker
and problem solved.

**Comment by jzdziarski** [comment]
Hello,
Thanks for the note; this was intentional, but as you've found, a behavior that can be easily changed by the user. I will be sure to add this to the readme. Thanks!
