### ISSUE TITLE
Don't steal focus with the alert window

### ISSUE THREAD

**Issue by farktronix** [jzdziarski/littleflocker#32]
The LittleFlocker alert window steals focus when it appears, which can quickly get frustrating if you're trying to type something but a background process is generating alerts.

New alerts should leave focus in the existing app, and if an alert is already shown, a new alert shouldn't appear over it.

**Comment by ne1for23** [comment]
Additionally, stealing focus could be badly timed while the user is pressing the enter (like a chat program) key thereby authorizing a filter alert without ever really getting to see it.

**Comment by jzdziarski** [comment]
Unfortunately, we have to steal focus to prevent anything in the background from hanging, I realize it can be frustrating, sorry. Once you get your initial rules set up for your software, you should have very few popups to deal with.

**Comment by farktronix** [comment]
Isn't it possible to pop up the window on top of all other windows but not steal keyboard focus?

**Comment by jzdziarski** [comment]
unfortunately not
