### ISSUE TITLE
I keep getting alerts after disabling LittleFlocker

### ISSUE THREAD

**Issue by farktronix** [jzdziarski/littleflocker#34]
I installed LittleFlocker, rebooted, and got lots of alerts. I disabled LittleFlocker but I keep having alerts pop up.

I grabbed a console log which I'm happy to share via email. Please contact me directly.

**Comment by farktronix** [comment]
I think these are all just queued up alerts from after I rebooted when LittleFlocker was enabled. I did a `kill -9` of the LittleFlockerDaemon and Little Flocker processes and after dismissing the alert no more popped up.

It looks like disabling LittleFlocker needs to tear down any in-flight requests.

**Comment by farktronix** [comment]
This was with the 0.2.0 release, FWIW. I just noticed that 0.3.1 is available now so I'm upgrading.

**Comment by jzdziarski** [comment]
This functionality will be released in a bugfix with 0.3.2. Thanks.
