### ISSUE TITLE
Provide a default set of rules to avoid first time alert madness for the default system applications

### ISSUE THREAD

**Issue by farktronix** [jzdziarski/littleflocker#35]
The first time I ran LittleFlocker I had to deal with a lot of alerts for system processes accessing the `.TemporaryItems` directory. 

It would be great if LittleFlocker had an option to start with a default set of rules that allows access for the default Apple system apps to locations like temporary items, and for Mail to the mail folder, Photos to the Photo Library, etc.

**Comment by jzdziarski** [comment]
Hello,
There is a set of default rules, but behavior is going to be different for everyone. If you've encountered some prompts that you don't think you should've gotten, please include them in this issue and I'll take a look at them to add to the default ruleset.

**Comment by farktronix** [comment]
It looks like I was running 0.2.0 and it didn't have any default rules. After upgrading to 0.3.1 I see lots more default rules. 👍

**Comment by jzdziarski** [comment]
0.2 did have default rules however they weren't visible in the configuration editor.... so if you've got some rules saved that you think should be in the default please pass them along. I'm not sure what this .TemporaryItems folder is you're talking about; if some third party application is using it, it may be something application specific. most good programs use the standard apple temp folders, which LF allows by default.

**Comment by farktronix** [comment]
It looks like the path was `/Volumes/Data/.TemporaryItems` because my home directory is on a different partition. I pasted all of my rules into #30

**Comment by jzdziarski** [comment]
The allow all rule you created should be fine for that; going to leave it out of the default rules, since the volume could change to whatever the user decides to use.
