### ISSUE TITLE
LittleFlocker prevented its own update

### ISSUE THREAD

**Issue by farktronix** [jzdziarski/littleflocker#36]
I installed LittleFlocker 0.2.0, then checked for updates and was told that 0.3.1 was available. I updated and the installer ran. I disabled LittleFlocker (the menu item is showing a ⚠️) before the update, but during the install I got a tamper warning alert.

<img width="532" alt="screen shot 2016-09-01 at 1 20 51 pm" src="https://cloud.githubusercontent.com/assets/4943/18182948/ee18eef2-7046-11e6-9e63-2e52f55f73d8.png">

I grabbed a console log which I'm happy to share via email.

**Comment by jzdziarski** [comment]
that's very unusual, did you get a popup telling you it was disabled? upgrades have been working smoothly for me. did the upgrade fail? Please reboot and give it another try if it did not succeed, make sure you disable LF before running the update.

**Comment by farktronix** [comment]
To be clear about the steps, I had disabled LittleFlocker earlier, rebooted, and after my machine started back up LittleFlocker still showed as disabled. I then checked for updates and ran the installer.

I quit the autoupdater, turned LittleFlocker on and back off again, and then ran the update and it worked.

It looks like the issue might be that LittleFlocker was enabled after a reboot even though the menu item showed that it was disabled. I also wasn't getting any alerts for processes, so it was in a weird half-enabled state.

**Comment by jzdziarski** [comment]
ah, okay, if you reboot while disabled, it comes up disabled, but still protects its own files from uninstall. you'll need to enable and then re-disable it. I am working on a UI fix for this to warn the user.

**Comment by jzdziarski** [comment]
going to close this out as it's a known issue, will need to enable and then disable LF to upgrade if you booted with it already disabled.

**Comment by farktronix** [comment]
Sounds good. Thanks for the quick response!
