### ISSUE TITLE
Mac freezes after initial installation

### ISSUE THREAD

**Issue by dlo** [jzdziarski/littleflocker#41]
First off, thanks @jzdziarski for this amazing tool!

Unfortunately, I had to uninstall Little Flocker since my system would freeze on boot after 4-5 popups asking for file read/access permissions were displayed. After giving access to those couple of processes, nothing loads and no applications start up.

**Comment by jzdziarski** [comment]
hi, if you can send me the /Library/Logs/LittleFlockerDaemon.log, i can take a look

**Comment by dlo** [comment]
Attached below, encrypted with your PK published at http://www.zdziarski.com/blog/?page_id=216 with fingerprint 2CC9 08AA 38C8 65B0 6C40  C0C9 F0F7 889A 55D4 9CC8.

[LittleFlockerDaemon.log.gpg.txt](https://github.com/jzdziarski/littleflocker/files/457467/LittleFlockerDaemon.log.gpg.txt)

**Comment by jzdziarski** [comment]
Well your system definitely has enough interesting things going on to give LF a good workout :) I'll take a close look at this and see what I can find. I'm not sure why it would freeze up after you're already logged in and getting popups.

**Comment by jzdziarski** [comment]
btw was this 0.99.0 or 0.99.1? i've made some changes in 0.99.1 that may or may not help you, but it will also improve logging for cases like this.

**Comment by dlo** [comment]
Maybe the first few minutes of logs were 0.99.0, but I upgraded after the first or second boot.

**Comment by jzdziarski** [comment]
did it hang up right after /Applications/Utilities/Adobe Creative Cloud/CCLibrary/CCLibrary.app/Contents/libs/node (832)

?

**Comment by dlo** [comment]
Yep, that seems right :). However, I think there were a few cases where it happened after another process.

**Comment by jzdziarski** [comment]
aha. i found it. my handling of processes that prematurely exit is... well, brain dead. i've fixed it. when 0.99.2 drops later today, i'd be grateful if you could give it another go.

**Comment by dlo** [comment]
Nice! Will do :)

**Comment by dlo** [comment]
Thanks so much for promptly addressing. :)

**Comment by jzdziarski** [comment]
actually, it would be great if we could be sure this is fixed ahead of releasing another maintenance release. i've attached the latest 0.99.2 build here, if you wouldn't mind confirming we're good. thanks!
[LittleFlocker-0.99.2.dmg.zip](https://github.com/jzdziarski/littleflocker/files/457543/LittleFlocker-0.99.2.dmg.zip)

**Comment by dlo** [comment]
Stepped out for a bit. Give me a few minutes and I'll try it out. :)

**Comment by jzdziarski** [comment]
a few others have tested with creative cloud and it's been working, so ive gone and pushed the official 0.99.2, i'd recommend using that one, let me know if you have any hangs

**Comment by dlo** [comment]
Nice! Will do.

**Comment by jzdziarski** [comment]
Have not heard back about this, going to close ticket. Note: 0.99.3 has now been released, which not only includes the fix for this from 0.99.2, but also a safe boot / first run option that will further help prevent any kind of boot hang.
