### ISSUE TITLE
Cannot disable or uninstall

### ISSUE THREAD

**Issue by scalefree** [jzdziarski/littleflocker#43]
After the first several rules were enabled things started going wonky. Apps started complaining about not being able to access resources or not starting at all, hanging on open. FF itself will not disable & the rule editor won't open. After a fresh boot I managed to open a shell & ran the uninstall script as root; I got a lot of "rm: operation not permitted". At some point FF asked to update & I said yes. What did I have to lose? That failed too, no permission to write to disk.  Oh I did copy the logfile but I can't even cat it. I am seriously wedged here.

**Comment by jzdziarski** [comment]
I think these issues were resolved in 0.99.2, to disable the version you have installed now, there are instructions in the read me file inside the dmg; it basically involves recovery mode and deleting some files. once you have it removed, give 0.99.2 a go and see if that resolves your hang issue.

**Comment by scalefree** [comment]
Are the instructions anywhere outside the dmg?  Like I said I can't even cat files right now, I'm working from my phone now.

**Comment by jzdziarski** [comment]
here you go:

For Beta Testers

As always is the case with beta software, things can go wrong. In the unlikely change that you find your system hung and will not boot, or other irrecoverable situations, perform the following steps to forcefully disable Little Flocker:

1. Boot into recovery mode using Command-R on boot
2. If your disk is FileVault protected, go into Disk Utility; select your disk and then select File > Mount. You'll be prompted for your account password to unlock the volume. Once unlocked, quit Disk Utility and return to the main recovery screen.
3. Select Utilities > Terminal to launch a terminal session
4. Run the following command to delete the Little Flocker kernel extension: 

rm -rf "/Volumes/Macintosh HD/Library/Extensions/LittleFlocker.kext”

5. Reboot, and then run the Little Flocker uninstall script to clean up

If things still fail, and the system is really mucked up, follow the instructions on this page to rebuild the entire pre-linked kernel:

https://discussions.apple.com/thread/7298047?start=0&tstart=0

**Comment by scalefree** [comment]
Uninstalled .99.1, installed .99.2.  System comes up very slowly & parts don't work at all (System Prefs - that may be a FF permission problem?)  Took several minutes for FF Rule Config to come up.  I've uninstalled again for now so I can use my system.  I really support the idea of this & want it to work but on my system, it just isn't.  I'll run through it once more & hopefully be able to give you the logfile.

**Comment by jzdziarski** [comment]
Glad you got it back up. If you send me your /Library/Logs/LittleFlockerDaemon.log and LittleFlockerFailsafe.log (if there is one) I can see what's going on in your system and advise.

**Comment by jzdziarski** [comment]
I've release 0.99.3, which has added a "safe boot" at first run and should present you with a list of suggested rules based on whatever is trying to access files on first boot. If you are still interested, please give this a try and let me know what results you get. I could still use your LittleFlockerDaemon.log file as well.

**Comment by jzdziarski** [comment]
going to close this out, but if you still have any problems with the latest betas, please let me know

**Comment by scalefree** [comment]
Sorry I didn't get back to you earlier with my logs but I just installed
.99.6 & all seems well.  This is an awesome addition to my security
posture, thanks so much for making it.

Tim

**Comment by scalefree** [comment]
Here's the LF daemon log.

Tim

**Comment by Gatewayy** [comment]
Where is the uninstaller script located?

**Comment by ne1for23** [comment]
@Gatewayy :  From the User Guide:  sudo bash /Library/LittleFlocker/uninstall.sh

**Comment by Gatewayy** [comment]
@ne1for23 Thanks for that, I read the User Guide but never cam across the actual location of the script.
