### ISSUE TITLE
System freezes if Littleflocker is enabled and I open jdownloader

### ISSUE THREAD

**Issue by necrevistonnezr** [jzdziarski/littleflocker#46]
macOS 10.12 Beta (16A313a), littleflocker 0.99.5

If littleflocker is enabled and I open jdownloader (see http://jdownloader.org/home/index?s=lng_en open source downloadmanager written in java), the system freezes completely. I have to hard reset and reboot.

Is there a log that I can help you with?

**Comment by ne1for23** [comment]
Yes, please send /Library/Logs/LittleFlockerDaemon.log to jonathan@zdziarski.com

**Comment by necrevistonnezr** [comment]
Done. Many thanks for your help!

**Comment by jzdziarski** [comment]
installing it now, when does it freeze, when you run it after install? also, what version of LF are you running? 0.99.5?

**Comment by necrevistonnezr** [comment]
It was already installed before I installed Littleflocker. Freezes when I open the jdownloader app. Running 0.99.5.

**Comment by jzdziarski** [comment]
hmm since i can't reproduce it, could you delete your LittleFlockerDaemon.log, reboot, and then try again, and send me that new log after it freezes, so that I can eliminate all the noise?

**Comment by jzdziarski** [comment]
also, one thing that you could do is turn on learning mode, then run the app, and it should allow everything and learn whatever rules you might need... seeing what it recommends might be really helpful in debugging it too

**Comment by necrevistonnezr** [comment]
After turning on learning mode, starting jdownloader, closing jdownloader, stopping learning mode, starting jdownloader: everything works fine. 

These are the newly imported rules:
![screenshot at sep 08 15-07-58](https://cloud.githubusercontent.com/assets/8191935/18350467/6713466a-75d6-11e6-9a3c-f3d6715b4a8e.png)

**Comment by jzdziarski** [comment]
you could probably shorten that down to two rules (JDownloader 2.0/) 

glad it's working, I'd love to figure out why it froze. could not reproduce over here. if you find anything more, feel free to reopen this issue.
