### ISSUE TITLE
Unclear what red color rules mean in configuration window

### ISSUE THREAD

**Issue by tomtastic** [jzdziarski/littleflocker#48]
![config](https://cloud.githubusercontent.com/assets/302127/18382458/e66ec2d4-7678-11e6-9a10-78a9b179ae73.jpg)
From the file paths I presume these are files which no longer exist, but this is unclear, so would it possible to add a column or legend to this view indicating the difference between the red rules and the others?

**Comment by jzdziarski** [comment]
will add to the user manual...

also, you could be reducing your rules a lot by just selecting the directory off of the popup menu rather than allowing individual files.

**Comment by tomtastic** [comment]
Thanks, it's obvious once you know what it means but may confuse a new user who hasn't (some users simply wont) read the manual.
