### ISSUE TITLE
Truncated path view in configuration window

### ISSUE THREAD

**Issue by tomtastic** [jzdziarski/littleflocker#50]
There doesn't seem to be a reason to truncate the view of the path here?
![truncated](https://cloud.githubusercontent.com/assets/302127/18384840/d062dee2-7684-11e6-919e-0da5f90cf5d2.jpg)

Could we have the available length at least the width of a modern screen, I'd rather not click into each rule and then have to view the path in a non-resizable  text box.

**Comment by jzdziarski** [comment]
thanks, this will be corrected in the next release
