### ISSUE TITLE
Rule edit didnt take effect until restart.

### ISSUE THREAD

**Issue by tomtastic** [jzdziarski/littleflocker#51]
I edited an existing rule to change the (java invoked auto-generated temporary name) application (as seen in second screenshot) to 'any', in efforts to allow any application run via java to access a specific direct path.

![any_via_java](https://cloud.githubusercontent.com/assets/302127/18385354/f5469610-7687-11e6-8fae-4e465deed294.jpg)

However, it appears not to work as re-launching this application requires me to create new rules again, so the matching for 'any' seems not to work in this case?

![any_via_java_fail](https://cloud.githubusercontent.com/assets/302127/18385378/232ce340-7688-11e6-92bd-b26a42be90f0.jpg)

**Comment by tomtastic** [comment]
Edit to say, I disabled and re-enabled LittleFlocker and the 'allow any via java' rules now work?
Curious why they only took effect after a re-load...

(this was all tested with v0.99.6)

**Comment by jzdziarski** [comment]
That's correct, rules edits don't take effect either until a restart or until you do an Advanced Options > Reload All Rules; it's a security necessity, in that the daemon has to confirm with the user before reloading or changing anything... otherwise it makes attacking the system much easier.

**Comment by tomtastic** [comment]
Ahha, well that make sense then, thank you.
Any chance of a warning indicator to remind users that changes aren't yet in effect?

Perhaps a traffic light system where the menu icon is be green when enabled and using up to date rules, yellow when rules aren't yet applied, and red when disabled?
