### ISSUE TITLE
Flocker hangs on restart/shutdown

### ISSUE THREAD

**Issue by dixflatlinr** [jzdziarski/littleflocker#52]
Whenever LittleFlocker is active during a restart/shutdown the system hangs with a constant black screen.

**Comment by jzdziarski** [comment]
Hello,
What version of Little Flocker are you using? Can you post /Library/Logs/LittleFlockerDaemon.log?

**Comment by jzdziarski** [comment]
Hi, please also try:

1. Boot up
2. Activate "Learning Mode" from the Advanced Options menu
3. Reboot
4. Deactivate "Learning Mode"
5. See if Little Flocker recommends new rules to address this

Thanks

**Comment by dixflatlinr** [comment]
Cannot reproduce with 0.99.7. Sorry, I think it was a false alarm. The shutdown took more time than it used to be.

**Comment by jzdziarski** [comment]
now worries, going to close this out; if the problem surfaces again, feel free to reopen it.
