### ISSUE TITLE
VirtualBox VM hangs on boot

### ISSUE THREAD

**Issue by scalefree** [jzdziarski/littleflocker#53]
Running .99.6.  When I start a VM in VirtualBox (5.0.26 r108824) it hangs, either from cold boot or restoring from save.  I turn off FF & it comes right up.  Daemon Log sent in email.

**Comment by jzdziarski** [comment]
I don't think the daemon log ever came through, but i'm going to be releasing beta 3 today, i think might address this.

**Comment by tm23** [comment]
Sadly beta 3 does not fix it. Even under learning mode, starting/stopping VMs just stalls out.

**Comment by jzdziarski** [comment]
I never got your daemon log, can you resend directly to jonathan@zdziarski.com?

**Comment by tm23** [comment]
Will do, I just sent it over. Thanks.

**Comment by jzdziarski** [comment]
so looking at your logs, it looks like what you're saying is LF is running on the host machine (not the guest machine), and the VM does not have LF, but the VM is what's hanging, right?

if you add this rule and reboot your host, does this change anything?

allow prefix "/" "/Applications/VirtualBox.app/" rwcm

also, when you turn on learning mode, are you rebooting your host or your VM?

**Comment by scalefree** [comment]
Sorry for lack of clarity.  Yes, LF on host causes VB guest to hang.  I've stayed in Simple mode so far, haven't explored Advanced at all yet.  I'll add the rule & see how it goes.

**Comment by scalefree** [comment]
Fixed.
