### ISSUE TITLE
permissions not sticking between boots

### ISSUE THREAD

**Issue by scalefree** [jzdziarski/littleflocker#54]
Dropbox, Google Drive & Magic Prefs keep asking for permission every boot even when I say Forever.

**Comment by jzdziarski** [comment]
can you check to see if the rules are actually getting added to the rules file?

**Comment by scalefree** [comment]
I see the expected rules for all 3.  I'll try another reboot & verify it happens again.

**Comment by jzdziarski** [comment]
can you paste them to me so i can see what it’s saving?

**Comment by jzdziarski** [comment]
wait. ~/Library/Preferences/ is whitelisted. did you change the default rules?

**Comment by scalefree** [comment]
Oh & also LF Config itself keeps asking for access to the rules on boot.

**Comment by jzdziarski** [comment]
LF config is normal, i don't allow that to be forever, for security; any time you edit your rules, it should ask permission.

**Comment by scalefree** [comment]
Dropbox & Google Drive haven't appeared the last few boots.  If they reappear I'll reopen but there's nothing to fix for now.
