### ISSUE TITLE
Some UX/UI recommendations

### ISSUE THREAD

**Issue by dixflatlinr** [jzdziarski/littleflocker#55]
LF works like a charm, but when you take a look at the current popup it just doesn't drive your eyes to the important parts, so I did some remodeling. If you like it, feel free to use it (if you need a psd, let me know).

![flocker3](https://cloud.githubusercontent.com/assets/17043913/18413476/2c878a5e-77a9-11e6-9d46-66f36411edd2.png)

Also, please make the four options selectable by shortcuts, like O, Q, R, F. So when a request pops up, I can just press the given key, then hit Enter to apply the rule.

**Comment by jzdziarski** [comment]
Have experimented with a number of different windows; not presently possible to do anything prettier without abandoning CFUserNotification, which I'm not ready to do right now... that is the more secure notification window, compared to a user-agent based notification, which is subject to tampering, unfortunately.
