### ISSUE TITLE
rule parsing may break on valid pathnames containing " via "

### ISSUE THREAD

**Issue by brad2014** [jzdziarski/littleflocker#57]
I'm learning a lot by reading the code.  I apologize if this is the wrong place to note things I'm not understanding.

It looks like apps that contain the word " via " are causing me confusion.  My rule to deny it access to files isn't taking effect, and it looks funny in the rules window.

**Rule**: 
```
deny path "any" "$HOME/Applications/casa via romana.sh" rwc
```

Rules... window:
<img width="870" alt="screen shot 2016-09-10 at 9 10 28 pm" src="https://cloud.githubusercontent.com/assets/6502462/18415107/3022720e-779b-11e6-9d3a-bbd70f04b089.png">

How do I make such app paths representable as rules? A thought: Can Eve confuse the system by creating executables that contain the word " via " (or other strings that are picked out of the path data that you treat as delimiters), that bypass rules?

**Comment by jzdziarski** [comment]
Unfortunately, via is a reserved word right now, you wouldn't be able to create rules specifically for any apps that include " via " in the path. It wouldn't bypass rules, but rather could never be added as a new rule specifically for that app. A workaround is in the works, but still figuring out the best way to do it.

**Comment by brad2014** [comment]
Aside: I also think my example is unrelatedly problematic because environment variables are perhaps not allowed in the "Process" section. True?

**Comment by jzdziarski** [comment]
$HOME is treated as an internal variable, and is replaced with the user's home dir by the system, that's unrelated to env vars, which are not allowed

**Comment by jzdziarski** [comment]
i found an elegant solution for this, watch for it in beta 5 on monday :)
