### ISSUE TITLE
UI glitches with system rules

### ISSUE THREAD

**Issue by brad2014** [jzdziarski/littleflocker#58]
Some small things I noticed when displaying system rules intermixed with my user rules in the Rules... window.

- The "gear" icon marking system rules in the Rules... window indicates to me "settings" or "preferences", but clicking on it does nothing. Maybe use a padlock icon (to indicate read-only).
- When a system rule is selected, [CR] brings up the system rule dialog box, but [ESC] does not dismiss it (they work as expected for user rules).
- The dialog box for a system rule does not indicate (except obliquely by having an OK button rather than a Save button) that it is a system rule and therefore read-only. (Expected: the dialog box would explicitly state "system rule" or be marked with the "system rule" icon for system rules).
- The input fields of the dialog box for a system rule are editable.  Hitting OK silently discards any edits.  (I expected the fields to be read-only).

**Comment by jzdziarski** [comment]
fixes committed, will appear in the next release
