### ISSUE TITLE
"forever" rules aren't

### ISSUE THREAD

**Issue by endico** [jzdziarski/littleflocker#59]
I just installed 0.99.9 in simple mode. I've rebooted several times and I keep getting re-asked the same things over and over even though I have given 'forever' permission several times. 

There's too much to remember everything but one app that fails especially badly is Keybase. I try to start it and get a popup asking if its ok to use /Library. I give 'forever' permission and then it asks the same things 4 or 5 times in a row. By then its attempt to mount its remote filesystem on /keybase times out so I get a popup about that.

I have some extra Keybase.io invites. Would you like one?

In between boots its also forgetting my 'forever' rules for backblaze (a disk backup app) and probably other apps too but I haven't gotten that far yet because I keep rebooting to test things.

I originally thought this was a timing problem waiting for me to give permission to LittleFlockerConfirmation so I closed that app and rebooted again but that time the machine locked up so badly I didn't think it would come back. When it finally did I disabled flocker.

**Comment by jzdziarski** [comment]
can you post your user rules file?

**Comment by endico** [comment]
[dawnendico.flock.txt](https://github.com/jzdziarski/littleflocker/files/466390/dawnendico.flock.txt)

**Comment by jzdziarski** [comment]
it looks like the first handful of requests came because there are different binaries inside of the keybase app accessing files... but the last bunch were all the same. ill see if i can download keybase and try against the latest code

**Comment by endico** [comment]
Let me know if you need an invite

**Comment by jzdziarski** [comment]
found the problem, it looks to be related only to simple mode. the fix will be in beta 5. if you still have any problems after installing beta 5 when it's pushed, please reopen this. thanks.
