### ISSUE TITLE
Installation of latest version prohibits MacOS from booting

### ISSUE THREAD

**Issue by LeShadow** [jzdziarski/littleflocker#60]
So this is what happened (exactly):

1. I installed LittleFlocker
2. I restarted my macbook pro.
3. Upon reboot, I tried login in again
4. Macbook keeps rebooting when I try to login, I can't get into my macbook anymore.
5. I booted in Recovery mode
6. I deleted the kernel extension
7. Now I can boot in normal mode again without issues.

Anything I need to change to make this work?

**Comment by LeShadow** [comment]
Also,

there aren't any LF logs? :/

**Comment by jzdziarski** [comment]
Nothing in /Library/Logs/ ?

What version OS are you running?

**Comment by jzdziarski** [comment]
Also do you have any AV software on there?

**Comment by LeShadow** [comment]
@jzdziarski i'm running OS X 10.11.6

I only have logs from after I managed to remove the kernel extension.
I'm also running the Trend Micro Security Agent

**Comment by jzdziarski** [comment]
can you try it without the security agent and see if things work? if it's preventing LF from running, there may not be anything I can do about it; it'd have to be whitelisted.

**Comment by jzdziarski** [comment]
I installed the trial of Trend Micro Internet Security on 10.11.6, and it seems to run fine with beta 5, so give that a try when it's pushed; it's possible it could be something completely unrelated, or the fix could already be in there.

**Comment by jzdziarski** [comment]
i've just pushed beta 5, please give it a go and let me know if you get different results

**Comment by jzdziarski** [comment]
no response, closing
