### ISSUE TITLE
[GUI] rules don't appear to be updated automatically

### ISSUE THREAD

**Issue by rprimus** [jzdziarski/littleflocker#63]
Wed Sep 14 11:23:20 BST 2016

system info:
```
ProductName:	Mac OS X
ProductVersion:	10.11.6
BuildVersion:	15G1004
```

LF info:
```
Version 1.0 (1)
```

With Little Snitch,  whenever an application is updated,  any previous rules are flagged as invalid and the application coloured red.

While working on debugging an issue,  this required an application to be rebuilt (from HEAD) twice.

Restarting the app (after the new compile) did ask for new permissions,  however these were not reflected in the rules - there were only rules for the previous two versions.

Stopping the app, removing all rules for the (red) application and restarting did not re-prompt for the permissions, implying there were some rules in memory,  but not visible in the GUI ruleset.

### Questions:
1.  Is there a signal that can be passed to LF that will dump the current rules (so they can be compared to what's on disk)?
2.  Are there plans on colouring outdated ```via``` rules?  ,eg gpg2 via (outdated mutt)

### Notes:
1.  Exporting the rules produces a file with the same contents as the one in ```/Users/Shared/Little Flocker```
2.  A reboot does not change the ruleset
3.  Running the app (after reboot),  prompted for file permissions.  9 rules were added to the file,  however, these rules were not shown in the GUI.  The GUI ```Rules view``` needed to be manually refreshed.

**Comment by jzdziarski** [comment]
Rules don't get updated until you reload rules. In the latest source, you're prompted automatically when you're done editing. We also don't have a way to track temporary rules yet, which may be what you're experiencing.

**Comment by rprimus** [comment]
Wed Sep 14 12:31:00 BST 2016

Not temporary rules - former permanent ```via```rules the the ```via``` is now at a new version.

eg: 
```allow path "/Users/rprimus/.gnupg/" "/usr/local/Cellar/gnupg2/2.0.30_2/bin/gpg2 via /usr/local/Cellar/neomutt/20160910/bin/mutt" rwc```

not highlighted when new rule added:

```allow prefix "/Users/rprimus/.gnupg/" "/usr/local/Cellar/gnupg2/2.0.30_2/bin/gpg2 via /usr/local/Cellar/neomutt/HEAD-49f2eff/bin/mutt" rwc```

**Comment by jzdziarski** [comment]
okay, so making sure i understand this correctly, you deleted /usr/local/Cellar/neomutt/20160910/bin/mutt but that rule didn't show up in red like it should have, correct?

**Comment by jzdziarski** [comment]
It's in the source repo now to color the item red if the parent path no longer exists; if it's updated, however, to the same path, it stays black. The latter may be something that can be implemented in the future.

**Comment by rprimus** [comment]
On Wed, Sep 14, 2016 at 07:58:16AM -0700, Jonathan Zdziarski wrote:
> It's in the source repo now to color the item red if the parent path no longer exists; if it's updated, however, to the same path, it stays black. The latter may be something that can be implemented in the future.
> 

Thu 15 Sep 2016 01:12:01 BST

Worth considering if the user should be alerted if
the binary (although at the same path) has
changed?   eg being updated to new version or
replaced by attacker?

Not sure how Little Snitch does it,  but when
binary changes (SHA ?),  even still at same path,
the rules are marked/flagged.

-- 
-primus (Train yourself and be your own master.)
"First solve the problem, then code!"
Narrowness of experience leads to narrowness of imagination.
http://www.catb.org/esr/faqs/smart-questions.html
http://www.chiark.greenend.org.uk/~sgtatham/bugs.html

GPG Key: 0x28E92848DB3FB476
Key fingerprint: B0FB C67E 2E7E 7032 7FE6  7FBC 28E9 2848 DB3F B476

**Comment by rprimus** [comment]
Sat Sep 17 11:45:49 BST 2016

:+1: Thanks for making the change.  Can confirm that when an application has been changed/updated,  all references (direct and ```via```) are now flagged in ```red```.

**Comment by rprimus** [comment]
Sat Sep 17 11:55:09 BST 2016

As a final request,  would it be possible to have these ```invalid``` rules grouped together (like Little Snitch)?

**Comment by jzdziarski** [comment]
we should have that conversation in #56
