### ISSUE TITLE
'unetbootin' causes OSX lockup when LS enabled

### ISSUE THREAD

**Issue by tomtastic** [jzdziarski/littleflocker#65]
unetbootin (http://unetbootin.github.io/) causes a lockup on OSX 10.11.6 if the following '...' button is clicked to browse for a diskimage :
![img_1949](https://cloud.githubusercontent.com/assets/302127/18584659/2a9e2ba2-7c0a-11e6-988b-54967587b12d.JPG)

OSX no longer accepts any keyboard input and appears to freeze, no LS popups are seen.
No lockups are noticed if LS is disabled prior to opening unetbootin.

**Comment by tomtastic** [comment]
If learning mode is enabled prior to launching unetbootin then these rules are discovered.
When these are imported into the LS ruleset, no future lockups are observed.
![unetbootin](https://cloud.githubusercontent.com/assets/302127/18584947/f3ac78e0-7c0b-11e6-8e1a-b26c28c5611c.jpg)

**Comment by jzdziarski** [comment]
This was fixed with an addition to the default rules:

+allow path "any" "/System/Library/PrivateFrameworks/TCC.framework/Versions/A/Resources/tccd" rwc

and will be in the next release

**Comment by tomtastic** [comment]
Lovely, thanks again!
