### ISSUE TITLE
Google Chrome not respecting Contributed Rules

### ISSUE THREAD

**Issue by bpinto** [jzdziarski/littleflocker#66]
The following rules are defined on [Chrome's Contributed Rules](https://github.com/jzdziarski/littleflocker/blob/master/LittleFlockerDeploy/root/Users/Shared/Contributed%20Rules/Google%20Chrome.flock):
```
allow prefix "$HOME/Library/Application Support/Google/" "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome" rwc
allow prefix "$HOME/Library/Google/" "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome" rwc
```

It's, however, not on my Little Flocker system-wide installed rules:
```
Cookies-MacBook-Air:Mackup bpinto$ cat "/Library/Application Support/LittleFlocker/littleflocker.rc" | grep Chrome
Cookies-MacBook-Air:Mackup bpinto$ 
```

Therefore, I was requested to take an action when Google tried to access it. Isn't this configuration supposed to live there?

I'm using latest beta: `Little Flocker 0.99.60`

**Comment by jzdziarski** [comment]
contrib rules aren't automatically imported; they're just there for convenience. to import them, go into the rules editor, then file > import; this is just a shortcut to save you from popups if you import the rules before you install/use whatever software.

**Comment by bpinto** [comment]
Oh sweet! Thanks for the explanation!
