### ISSUE TITLE
popup keyboard navigation

### ISSUE THREAD

**Issue by ludalex** [jzdziarski/littleflocker#69]
With the previous versions you were able to navigate the frequency options with keyboard arrows and then press alt to select either "Deny" or "Allow" and press enter.

With the latest version it appears that this is no longer possible and I'd think it would be nice to reintroduce it as it's a huge time saver, especially at the beginning when you get a lot of popups.

**Comment by jzdziarski** [comment]
Hi, the keys have changed but there are still hot keys. Check out the user guide for more details.

**Comment by chamunks** [comment]
Sorry about the ignorance but where is this user guide. https://github.com/jzdziarski/littleflocker?files=1#documentation

**Comment by jzdziarski** [comment]
in the dmg

**Comment by ludalex** [comment]
Thanks. IMHO the user guide should be in the repo wiki as well. That's were I'd personally go to look for it.

**Comment by jzdziarski** [comment]
A wiki will eventually come but too busy with project dev ATM
