### ISSUE TITLE
Where is the User Guide

### ISSUE THREAD

**Issue by chamunks** [jzdziarski/littleflocker#71]
There are several references to this user guide but no option to open it from inside the app or any real obvious results on google as to what you're referring to.
https://github.com/jzdziarski/littleflocker/issues/70

**Comment by jzdziarski** [comment]
it shows up right next to the installation package when you click the DMG; there's no reason anyone shouldn't see it.

**Comment by jzdziarski** [comment]
it is also right at the root of the source tree, you must not be looking for it

**Comment by chamunks** [comment]
I was looking on google and through your site and through the various menus on the application assuming that'd be where it was.  My apologies I assumed that when you closed the ticket it was the end of the discussion on that question so opening a new ticket was the next logical thing to do.  

Is there link where [this](https://github.com/jzdziarski/littleflocker/tree/master/User%20Guide.rtfd) can be accessed online or is only in the install package because I only see the install package on the first install not during updates.  I have my computer setup to automagically delete .dmg files after about a day so I avoid clutter.

**Comment by jzdziarski** [comment]
i'm sorry if it's too hard for you to find it, it's right at the top of the git tree, labeled "User Guide" and it shows up RIGHT NEXT TO the package file when you double click the DMG. Anyone who's looking should be able to find it. You should click on user guides before you ever run the package in the first place. This is a classic case of not wanting to read the manual.

**Comment by chamunks** [comment]
I found it and linked it in my last response. 
https://github.com/jzdziarski/littleflocker/tree/master/User%20Guide.rtfd but this isn't the version I got from inside of the DMG.  

There is really no reason to be so abrasive.

**Comment by jzdziarski** [comment]
That's the exact same thing that's in the DMG, it's copied directly in from that file. I am only abrasive because it's incredibly rude to open three consecutive tickets on the same topic.

**Comment by chamunks** [comment]
Its not difficult to see the manual before the app is installed but the problem that I'm trying to convey is that once it's been installed.  You have to re-download the original DMG file in order to view it again.  Am I really that crazy for thinking that this is slightly less than convenient?  

I had gleaned enough information from reading other documentation and tutorials on the application otherwise I wouldn't have installed the app itself its a bit presumptuous to assume that I'd just downloaded some app willy nilly.  I've been running this app for about a month now and wanted to simply increase my overall abilities with it.

**Comment by jzdziarski** [comment]
yes i think that's unreasonable.
