### ISSUE TITLE
Feature request: a link to the User Guide from the app's context menu.

### ISSUE THREAD

**Issue by chamunks** [jzdziarski/littleflocker#72]
It would be brilliant to not have to re-download the original [DMG file](https://github.com/jzdziarski/littleflocker/issues/71) in order to review the User Guide potentially utilizing some kind of magic linking to the Github Wiki or some other online repository.  Potentially an Markdown file variant which can be directly linked to the specific commit/build that is installed.

Also thank you for your time and attention to this matter.  Your application is brilliant.

**Comment by jzdziarski** [comment]
please stop opening new tickets about this, the user's guide is very easy to find for anyone looking for it.

**Comment by chamunks** [comment]
I would stop opening new tickets about this if you'd stop closing the tickets before the line of questions were completed.

**Comment by jzdziarski** [comment]
if you don't cut the shit you're going to find your account blocked.
