### ISSUE TITLE
Standard Users Not Supported?

### ISSUE THREAD

**Issue by Aktariel** [jzdziarski/littleflocker#74]
I started using beta 3 of Little Flocker, and in all the time since then it has notified me...never, of any attempts by any applications to access files. I was a bit confused, but when I manually went to make a "New Rule," I got a notification about standard users not being allowed to add rules (or something to that effect; I did not unfortunately take a screenshot). 

I've since updated to Beta 6, which does not have the warning when I attempt to manually add a rule, but it has also never notified me of any attempts to access files. I've uninstalled and reinstalled, with the same effect.

I'm currently running macOS Sierra 10.12 (16A320).

I have two users on my machine, an administrator account that I only use to install trusted applications, and a standard user that I use regularly. (The standard user also has sudo access, and is the only user trusted to unlock the FIleVault volume). Will I only see the benefit to Little Flocker if I use the admin account?

**Comment by jzdziarski** [comment]
Hi-

By default, yes, but I've put some settings into the default config that you can tweak in order to customize it for what you need. Eventually I hope to make these GUI accessible. For now, check out /Library/Application Support/LittleFlocker/littleflocker.rc (can only edit the file when disabled); there are some notes near the beginning on setting up non-admin rule capabilities for the system. It defaults to only allowing admins to create rules (parental control type setup), but you can, with a couple changes and a chmod, set it up so you can make them in your non-admin account.

**Comment by Aktariel** [comment]
I will take a look. 

Standard users tend to be the more-secure option (ounce of prevention etc) these days from preventing privilege escalations and malware infection from taking hold in the first place; are there any plans to extend Little Flocker's live protection to them?

**Comment by jzdziarski** [comment]
LF should appear and warn for standard users (at least it does here, on my family machine); it just doesn't allow them to make rules... so if you're not getting prompted at ALL, something's wrong. Did you install it as admin? That would be the first thing I'd make sure of.

**Comment by Aktariel** [comment]
Correct - I have seen exactly 0 popups during my use of Little Flocker. 

I provided an admin username and password during installation, but ran said installation from the standard user.

I will uninstall and reinstall while logged into the admin user, and report back.

**Comment by jzdziarski** [comment]
that is likely the reason; i would be sure you're logged in as the admin user and give it another try.

**Comment by Aktariel** [comment]
Uninstalled, rebooted, logged out of standard user, logged into admin user, downloaded a fresh copy of beta 6, reinstalled, logged into standard user automatically after first reboot. 

Still not seeing any UI prompts. I imagine that Chrome or Word at least should generate warnings, but there is nothing of the kind. Is it because Little Flocker is not concerned about, and therefore not warning about, access of any kind inside my home folder? I don't imagine that to be the case.

**Comment by jzdziarski** [comment]
You're going to want to be logged in as admin on first reboot to set it up as well.

If that doesn't work can you send me /Library/Logs/LittleFlockerDaemon.log ?

Also check and make sure you have:
/Library/Extensions/LittleFlocker.kext
/Library/LittleFlocker/LittleFlockerDaemon

**Comment by Aktariel** [comment]
The issue here is very interesting, and I believe is related to FileVault.

The admin user does not have permission to unlock the volume, so the computer always boots to the Standard User desktop, which does not allow for LittleFlocker to set up and run. Logging out and into the admin user seems to set up Little Flocker properly (there's the firehose I was expecting). I'll report back if prompts are still not appearing.

Probably not something you can fix, since this is not a terribly standard configuration, but interesting nonetheless.

**Comment by jzdziarski** [comment]
i'll be sure to add to the user guide that you have to be logged in as an admin to install and after first run. thanks for reporting back.

**Comment by Aktariel** [comment]
It would also be helpful if there was a way for standard users to reload rules - maybe as an option in the littleflocker.rc config file, even if not exposed through the GUI.

Thanks for the app, by the way. Works a treat now that I've got it sorted out. :)

**Comment by jzdziarski** [comment]
grab tomorrow's nightly (20160919) when it gets pushed in 24 hours, that functionality will be there
