### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by pwnsdx2** [jzdziarski/littleflocker#8]
I'm not a troll, you are. You really thought by deleting the old repository and banning/blocking me from the new one people would forget the issues that have been fixed? Well maybe you're right, maybe not, in the meantime take this one: https://gist.github.com/pwnsdx/e404fbed3814db8404634740f1e24176

**Comment by jzdziarski** [comment]
This is Apple's problem, not Little Flocker, but the idea of monitoring media insertions and network mounts is not a bad idea.
